# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Edbert Voo
      title: Go to homepage
      path: homepage
      class: first
    - label: About
      path: page/about
    - label: News
      path: entries/
    - label: Works
      path: works/
