# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false
    #listing_template: tag-listing.twig #custom template

groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true

worksgroups:
    name: Work Group
    slug: worksgroups
    singular_slug: worksgroup
    behaves_like: grouping
    options: { sample: "Samples", project: "Projects" }
    has_sortorder: true


workscategories:
    name: Work Categories
    slug: workscategories
    singular_name: Work Category
    singular_slug: workcategory
    behaves_like: categories
    multiple: true
    options: [ web, desktop, mobile, highlight ]

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ news, events, movies, music, books, life, love, fun, projects, samples, website ]
